Backend/package-lock.json
Backend/package.json
Backend/src/controllers/course.controller.ts
Backend/src/models/course.model.ts
Backend/src/routers/course.router.ts
Backend/src/server.ts
Backend/src/utils/helper.ts

added courseSchema, add/edit/delete/see all course controllers and course router

added course.controller.ts , course.model.ts , course.router.ts

---

Backend/src/controllers/booking.controller.ts
Backend/src/models/user.model.ts
Backend/src/routers/product.router.ts
Backend/src/routers/user.router.ts

I make bookingCourse and cancelBooking controllers
but I didnt test it yet

added booking.controller.ts

---

Backend/src/controllers/booking.controller.ts
Backend/src/middlewares/authRoleAdmin.ts
Backend/src/middlewares/authenticate.ts
Backend/src/routers/product.router.ts

I added authorizeRoles middleware
But i didn't test it yet

added authorizeRoles middleware

---

Backend/src/controllers/booking.controller.ts
Backend/src/controllers/cart.controller.ts
Backend/src/models/product.model.ts
Backend/src/routers/product.router.ts
Backend/src/routers/user.router.ts

I added simple adding/deleting controllers to put/delete a product to/from the cart
(i didn't concerned about counting number of same item in the cart when it happens)

added cart.controller.ts

---

Backend/src/controllers/cart.controller.ts
Backend/src/controllers/courseTemplate.controller.ts
Backend/src/models/courseTemplate.model.ts
Backend/src/routers/courseTemplate.router.ts
Backend/src/server.ts

I added course template model, route and controllers (to see all templates , to create new template , to delete template, to edit template).
and i tested it with Postman and it worked.

added courseTemplate model, route, controllers

---

Backend/src/controllers/admin.controller.ts
Backend/src/controllers/booking.controller.ts
Backend/src/routers/admin.router.ts
Backend/src/server.ts
Backend/src/utils/setWeeklyCourse.ts

added setWeeklyCourse.ts in utils directroy and function that set courses for in future weeks

added setWeeklyCourse.ts in utils directroy

---

Backend/package-lock.json
Backend/package.json
Backend/src/server.ts

added the function in server.ts that is going to run every sunday mornings to run another function that will set courses in 2 weeks.
I tested it and it works

added cron schedule function in server.ts

---

Frontend/src/components/Auth/Login.tsx

login request works with backend, 
also after you logged in successfully, you will redirect to different pages depends on role of user

login works with backend

---

Backend/src/controllers/admin.controller.ts
Backend/src/controllers/cart.controller.ts
Backend/src/controllers/order.controller.ts
Backend/src/controllers/user.controller.ts
Backend/src/middlewares/authAndRoles.ts
Backend/src/models/order.model.ts
Backend/src/models/product.model.ts
Backend/src/models/user.model.ts
Backend/src/routers/admin.router.ts
Backend/src/routers/user.router.ts
Backend/src/server.ts

- updated check roles middleware so multiple roles can be accepted
- cart now has quantity value
- 3 order routes for members and admins 
- 4 order routes for admin only

order controllers and routes

---

Backend/src/controllers/user.controller.ts
Backend/src/server.ts
Frontend/src/App.tsx
Frontend/src/components/Admin/CourseTemplates/CourseTemplateDisplay.tsx
Frontend/src/components/Admin/CourseTemplates/TemplateRequests.ts
Frontend/src/components/Admin/MembersTable/MembersTable.tsx
Frontend/src/components/Admin/MembersTable/RequestFunctions.ts
Frontend/src/components/Auth/Login.tsx
Frontend/src/components/Header/Header.tsx
Frontend/src/components/Layouts/AdminLayout.tsx
Frontend/src/components/Layouts/AdminRoute.tsx
Frontend/src/context/UserContext.tsx
Frontend/src/pages/AdminPage/AdminPage.tsx

User Context for LogIn information added. UseEffect for refresh of page checks for authentication (cookie) and sets user again. update on authentication controller (user Object and how its send back).

User context

---

Frontend/src/components/Dashboard/Dashboard.tsx
Frontend/src/components/Layouts/AdminLayout.tsx

i can see now data from database so function works 
but what we want to show is not done, so we make it better in the future

added database info to overview

---

Frontend/src/Layouts/AdminRoute.tsx
Frontend/src/components/Admin/AdminHeader.tsx
Frontend/src/components/Admin/CourseTable/CourseTable.tsx
Frontend/src/components/Auth/Login.tsx
Frontend/src/components/DummyData/courses.tsx
Frontend/src/context/UserContext.tsx
Frontend/src/main.tsx

Update for: 
AdminRoute
Login
UserContext
re-routing fixed, refresh works now

userContext, navigation, login, re-fresh fixed

---

Frontend/src/context/UserContext.tsx

userContext update, deleted AdminRoute and MembersRoute. Route protection centralized in Context

userContext centralized logic 

---

Backend/src/controllers/user.controller.ts
Frontend/src/context/UserContext.tsx

address, firstName, lastName, role, membership, _id in Context

userContext updated

---

Frontend/src/components/Auth/Login.tsx
Frontend/src/context/UserContext.tsx

updated login and Context
frontend (variable names and context setting) and backend (userModel update)

login and userContext updated

---

Backend/src/controllers/user.controller.ts
Backend/src/models/user.model.ts
Backend/src/validators/user.validator.ts
Frontend/src/App.tsx
Frontend/src/components/Admin/CourseTable/CourseTable.tsx
Frontend/src/components/Auth/Login.tsx
Frontend/src/context/DateContext.tsx

first updated user login and context (Again)

Course week calendar

---

Backend/src/controllers/order.controller.ts
Frontend/src/App.tsx
Frontend/src/components/Admin/AdminOrders/AdminOrders.tsx
Frontend/src/components/Admin/AdminSidebar/AdminSidebar.tsx
Frontend/src/components/Members/MemberSidebar.tsx

orders table  with basic search option for order number and product name
still needs other filtering options and/or maybe reorganize the table in different layout to display more information

orders page for admin

---

Backend/src/routers/user.router.ts
Frontend/src/components/Members/MemberHeader.tsx
Frontend/src/components/Members/MembersCourseTable.tsx

- logout for user added
- course route for user added
- highlight of booked courses added in calendar

course Route for users, logout added to header

---

Frontend/src/components/Members/BookedCourses.tsx
Frontend/src/components/Members/CourseCardForMember.tsx
Frontend/src/components/Members/MembersCourseTable.tsx

added new code that member can not book a pasted courses
and it doesn't appear in booked course page

added new code that member can not book a pasted courses

---

Frontend/src/App.tsx
Frontend/src/components/Admin/Courses/CourseTable/CourseCardForAdmin.tsx
Frontend/src/components/Admin/Orders/AdminOrders.tsx
Frontend/src/components/Members/Courses/CourseCardForMember.tsx
Frontend/src/components/Members/MemberSidebar.tsx
Frontend/src/components/Members/Orders/Orders.tsx
Frontend/src/components/Members/Profile/UserProfile.tsx
Frontend/src/custom.Types/orderTypes.ts

- fixed remaining issues with types
- changed some paths
- added reusable types for orders

small changes in orders pages

---

Frontend/src/components/Header/Header.tsx
Frontend/src/components/Members/Courses/MembersCourseTable.tsx
Frontend/src/context/DateContext.tsx

Course calendar

---

Frontend/src/components/Header/Header.tsx
Frontend/src/components/Shop/Products.tsx
Frontend/src/context/CartContext.tsx

- quantity on cart icon
- change icon to tick when adding product to cart
- if product is out of stock then add to cart button is disabled

cart changes

---

Frontend/src/components/Admin/Courses/CourseTemplates/CourseTemplateDisplay.tsx
Frontend/src/components/Admin/MembersTable/MembersTable.tsx
Frontend/src/components/Landingpage/CourseGallery/CourseGallery.tsx
Frontend/src/components/Members/Courses/CourseCardForMember.tsx
Frontend/src/pages/CoursesPage/CoursesPage.tsx
Frontend/src/utils/URL.ts

added filter option for course templates (admin)
updated course pics landing page
updated filter for public course page (no duplicates)
re-fetch when cancelling booked course (members)

course templates update, course pics update

---

Backend/src/controllers/user.controller.ts
Frontend/src/App.tsx
Frontend/src/Layouts/PublicLayout.tsx
Frontend/src/components/Auth/ForgotPass.tsx
Frontend/src/components/Auth/Login.tsx
Frontend/src/components/Auth/PassResetHandlePage.tsx
Frontend/src/components/Auth/UserNotFound.tsx
Frontend/src/components/Auth/VerifyHandlePage.tsx
Frontend/src/components/Page404.tsx

added forgot password function, page, and changed a little bit of code in VerifyResetLink controller
I tested with frondend and it works

forgot password function done

---

Backend/src/controllers/contact.controller.ts
Backend/src/models/contact.model.ts
Backend/src/routers/admin.router.ts
Backend/src/routers/contact.router.ts
Backend/src/routers/public.router.ts
Backend/src/server.ts
Backend/src/utils/emailService.ts
Frontend/src/App.tsx
Frontend/src/Layouts/AdminLayout.tsx
Frontend/src/components/Admin/AdminSidebar.tsx
Frontend/src/components/Admin/Messages/Messages.tsx
Frontend/src/components/Header/Header.tsx
Frontend/src/pages/ContactPage/ContactPage.tsx
Frontend/src/pages/ContactPage/contact.css
Frontend/src/utils/URL.ts

1. Added contact controler, route and model in backend
2. added contact page on public layout with contact form. Email goes to our mail.de email and to database
3. Displayed all emails on messages page for admins from database

Contact page on public and messages page on admin layout

---

Frontend/src/components/Admin/AdminOrders/AdminOrders.tsx
Frontend/src/components/Auth/Login.tsx
Frontend/src/components/Landingpage/Hero/Hero.tsx
Frontend/src/components/Members/MemberOrders/MemberOrders.tsx

- when loggin in now users can hit enter with keyboard without triggering forgot password link
- orders are sorted by newest first on the top
- landing page hero button goes to shop

some bugs fixed
